include: package:lints/recommended.yaml

analyzer:
  errors:
    constant_identifier_names: ignore
    file_names: ignore
    non_constant_identifier_names: ignore
  exclude:
    - dartsdk_download/**
    - dartsdk_download-temp/**
    - build-gradle/**
    - .dart_tool/**

formatter:
  page_width: 120