name: matssocket
version: 0.18.0+2021-09-19
description: MatsSocket Dart client library
repository: https://github.com/centiservice/matssocket

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  logging: ^1.0.2

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.17.12
  test_api: ^0.4.3