name: matssocket
version: 0.19.0+2022-11-11
description: >
  MatsSocket client library employing WebSockets to bridge the asynchronous message
  based nature of server-side Mats^3 out to end user client applications
repository: https://github.com/centiservice/matssocket

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  logging: ^1.3.0

dev_dependencies:
  http: ^1.5.0
  web: ^1.1.1
  lints: ^6.0.0
  test: ^1.26.2