name: matssocket
version: 1.0.0+2025-10-27
description: >
  MatsSocket client library employing WebSockets to bridge the asynchronous message
  based nature of server-side Mats^3 out to end user client applications
repository: https://github.com/centiservice/matssocket

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  logging: ^1.3.0
  web: ^1.1.1    # Only for the JS/node/web version via conditional import, provides WebSocket and web.window
  http: ^1.5.0   # Only for the JS/node/web version via conditional import, provides BrowserClient

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
