name: matssocket
version: 0.19.0+2022-11-11
description: >
  MatsSocket client library employing WebSockets to bridge the asynchronous message
  based nature of server-side Mats^3 out to end user client applications
repository: https://github.com/centiservice/matssocket

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  logging: ^1.0.2

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.17.12
  test_api: ^0.4.3
  http: ^0.13.5